name: Run Playwright Smoke Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  schedule:
    # Runs automatically every day at 02:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chromium'
        type: choice
        options:
          - 'chromium'
          - 'firefox'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      env:
        UI_PROJECT: ${{ inputs.browser || 'chromium' }}
        UI_BASE_URL: ${{ secrets.UI_BASE_URL }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        API_ADMIN_USERNAME: ${{ secrets.API_ADMIN_USERNAME }}
        API_ADMIN_PASSWORD: ${{ secrets.API_ADMIN_PASSWORD }}
        UI_TEST_USERNAME: ${{ secrets.UI_TEST_USERNAME }}
        UI_TEST_EMAIL: ${{ secrets.UI_TEST_EMAIL }}
        UI_TEST_PASSWORD: ${{ secrets.UI_TEST_PASSWORD }}
      run: npm run test:smoke:$UI_PROJECT
      #backup
    - name: Upload Monocart Report & Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: monocart-report
        path: monocart-report/
        retention-days: 5

  # Publish Monocart Report to GitHub Pages
    - name: Deploy Monocart Report to GitHub Pages
      if: ${{ !cancelled() }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./monocart-report      
